@startuml
Sender -> Telephone : Input Number
Telephone -> Sender : [Invalid Number] Number Not Found
Telephone -> Receiver : [Valid Number]Call to Receiver
Receiver -> Telephone : [Invalid Receiver] Can't call to receiver

@enduml