@startuml telephone1
actor Sender
participant "Sender's Telephone" as ST
participant "Receiver's Telephone" as RT
actor Receiver

Sender -> ST : ยกหู
Sender -> ST : ใส่เบอร์
ST -> RT : สัญญาณดัง
RT -> RT : สัญญาณดังไม่เกิน 30 วินาที
Receiver -> RT : ยกหู
RT -> ST : [ยกหูก่อน 30 วินาที] เชื่อมต่อ
ST -> Sender : ทำการเชื่อมต่อ
Sender -> ST : คุย
ST -> RT : รับสัญญาณเสียง
Receiver -> RT : คุย
RT -> ST : รับสัญญาณเสียง
ST ->  ST : สายซ้อน
Sender -> ST : กดเปลี่ยนสาย
ST -> RT : มีการเปลี่ยนสายตัดการเชื่อมต่อ
ST -> RT :จบการสนทนาตัดการเชื่อมต่อ
Sender -> ST : วางหู
Receiver -> RT : วางหู

@enduml
